name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | \
          docker login --username AWS --password-stdin 799771184674.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t shiv-ci .
          docker tag shiv-ci:latest 799771184674.dkr.ecr.eu-north-1.amazonaws.com/shiv-ecr-demo:latest

      - name: Push Image to ECR
        run: |
          docker push 799771184674.dkr.ecr.eu-north-1.amazonaws.com/shiv-ecr-demo:latest

      # ⭐ STEP 2: DECODE BASE64 PRIVATE KEY
      - name: Decode private key
        run: |
          echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 --decode > id_rsa
          chmod 600 id_rsa

      # ⭐ FINAL STEP: DEPLOY USING SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: id_rsa
          script: |
            chmod +x /home/ec2-user/deploy.sh
            /home/ec2-user/deploy.sh
